name: livehigh
favicon: null
layout_spectrum: 0.23379816417582333
typography_spectrum: 0.3050093736965209
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.47518655960448086
  lightness: 0.9386312037240714
  saturation: 0.7029462161008269
  rhythmicContrast: 0.11894800327718258
purpose: []
